#!/usr/bin/env bash
# 结构棘轮 Shell 合同测试。所有样例都在临时 Git 仓库中运行，不读取真实项目源码或构建缓存。
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
checker_source="$repo_root/scripts/check/layout.sh"
test_root=$(mktemp -d "${TMPDIR:-/tmp}/ubaa-layout-contract.XXXXXX")
trap 'rm -rf -- "$test_root"' EXIT HUP INT TERM

pass_count=0

fail() {
  printf 'not ok - %s\n' "$1" >&2
  exit 1
}

pass() {
  pass_count=$((pass_count + 1))
  printf 'ok %d - %s\n' "$pass_count" "$1"
}

# RED 前置：先在隔离 Git 仓库中证明生产 checker 尚不存在。
missing_repo="$test_root/checker-missing"
mkdir -p "$missing_repo"
git -C "$missing_repo" init -q
if [[ ! -f "$checker_source" ]]; then
  fail 'scripts/check/layout.sh 尚不存在（阶段 02 预期 RED）'
fi

new_repo() {
  local name=$1
  local repo="$test_root/$name"
  mkdir -p "$repo/scripts/check"
  git -C "$repo" init -q
  git -C "$repo" config user.name 'UBAA Layout Contract'
  git -C "$repo" config user.email 'layout-contract@example.invalid'
  cp "$checker_source" "$repo/scripts/check/layout.sh"
  chmod +x "$repo/scripts/check/layout.sh"
  printf '%s\n' '# kind<TAB>path<TAB>exact-count' >"$repo/scripts/layout-baseline.txt"
  printf '%s\n' "$repo"
}

write_source_lines() {
  local path=$1
  local count=$2
  local prefix='// 合同测试行'
  local line
  mkdir -p "$(dirname "$path")"
  if [[ $path == *.sh ]]; then
    prefix='# 合同测试行'
  fi
  : >"$path"
  for ((line = 1; line <= count; line += 1)); do
    printf '%s %04d\n' "$prefix" "$line" >>"$path"
  done
}

write_generated_lines() {
  local path=$1
  local count=$2
  local line
  mkdir -p "$(dirname "$path")"
  {
    printf '%s\n' '// This file is automatically generated, so please do not edit it.'
    printf '%s\n' '// @generated by `flutter_rust_bridge`@ 2.13.0.'
    for ((line = 3; line <= count; line += 1)); do
      printf '// generated contract line %04d\n' "$line"
    done
  } >"$path"
}

commit_all() {
  local repo=$1
  git -C "$repo" add -A
  git -C "$repo" commit -qm '准备结构合同样例'
}

run_checker() {
  local repo=$1
  (
    cd "$repo"
    bash scripts/check/layout.sh
  )
}

expect_pass() {
  local name=$1
  local repo=$2
  local output status
  set +e
  output=$(run_checker "$repo" 2>&1)
  status=$?
  set -e
  if [[ $status -ne 0 ]]; then
    printf '%s\n' "$output" >&2
    fail "${name}：预期通过，实际退出码 $status"
  fi
  pass "$name"
}

expect_rejected() {
  local name=$1
  local repo=$2
  local expected_path=$3
  local output status
  set +e
  output=$(run_checker "$repo" 2>&1)
  status=$?
  set -e
  if [[ $status -eq 0 ]]; then
    fail "${name}：预期拒绝，实际通过"
  fi
  if [[ $output != *"$expected_path"* ]]; then
    printf '%s\n' "$output" >&2
    fail "${name}：诊断未包含相对路径 $expected_path"
  fi
  pass "$name"
}

# 边界值本身必须通过：1000 行、一个目录 16 个直属手写源码。
repo=$(new_repo boundary)
write_source_lines "$repo/src/boundary.rs" 1000
for number in {01..16}; do
  write_source_lines "$repo/src/sixteen/file_${number}.dart" 1
done
commit_all "$repo"
expect_pass '1000 行与 16 个直属源码是允许边界' "$repo"

# 已提交的超长文件与拥挤目录都必须被拒绝。
repo=$(new_repo tracked-too-long)
write_source_lines "$repo/src/tracked.rs" 1001
commit_all "$repo"
expect_rejected '已提交超长文件会失败' "$repo" 'src/tracked.rs'

repo=$(new_repo crowded-directory)
for number in {01..17}; do
  write_source_lines "$repo/src/crowded/file_${number}.rs" 1
done
commit_all "$repo"
expect_rejected '17 个直属手写源码的目录会失败' "$repo" 'src/crowded'

# baseline 只接受相同路径、相同种类和相同数量的现存违例。
repo=$(new_repo accepted-baseline)
write_source_lines "$repo/src/legacy.rs" 1001
for number in {01..17}; do
  write_source_lines "$repo/src/legacy_dir/file_${number}.kt" 1
done
printf 'file\tsrc/legacy.rs\t1001\n' >>"$repo/scripts/layout-baseline.txt"
printf 'dir\tsrc/legacy_dir\t17\n' >>"$repo/scripts/layout-baseline.txt"
commit_all "$repo"
expect_pass '精确 baseline 允许现存文件与目录违例' "$repo"

repo=$(new_repo stale-file-baseline)
write_source_lines "$repo/src/legacy.rs" 1002
printf 'file\tsrc/legacy.rs\t1001\n' >>"$repo/scripts/layout-baseline.txt"
commit_all "$repo"
expect_rejected '文件数量变化使 baseline 陈旧' "$repo" 'src/legacy.rs'

repo=$(new_repo resolved-file-baseline)
write_source_lines "$repo/src/resolved.rs" 1000
printf 'file\tsrc/resolved.rs\t1001\n' >>"$repo/scripts/layout-baseline.txt"
commit_all "$repo"
expect_rejected '已修复文件仍留在 baseline 会失败' "$repo" 'src/resolved.rs'

repo=$(new_repo stale-directory-baseline)
for number in {01..18}; do
  write_source_lines "$repo/src/legacy_dir/file_${number}.ets" 1
done
printf 'dir\tsrc/legacy_dir\t17\n' >>"$repo/scripts/layout-baseline.txt"
commit_all "$repo"
expect_rejected '目录数量变化使 baseline 陈旧' "$repo" 'src/legacy_dir'

# index 中的 staged 文件和未忽略 untracked 文件不能绕过扫描。
repo=$(new_repo staged-source)
commit_all "$repo"
write_source_lines "$repo/src/staged.kt" 1001
git -C "$repo" add src/staged.kt
expect_rejected 'staged 超长源码会失败' "$repo" 'src/staged.kt'

repo=$(new_repo untracked-source)
commit_all "$repo"
write_source_lines "$repo/src/untracked.swift" 1001
expect_rejected '未忽略 untracked 超长源码会失败' "$repo" 'src/untracked.swift'

# 同一路径的 index blob 与工作树内容必须分别检查，不能以另一份较短内容掩盖超长版本。
repo=$(new_repo staged-long-worktree-short)
write_source_lines "$repo/src/diverged.rs" 1
commit_all "$repo"
write_source_lines "$repo/src/diverged.rs" 1001
git -C "$repo" add src/diverged.rs
write_source_lines "$repo/src/diverged.rs" 1000
expect_rejected 'index 超长而工作树合规仍会失败' "$repo" 'src/diverged.rs'

repo=$(new_repo staged-short-worktree-long)
write_source_lines "$repo/src/diverged.rs" 1
commit_all "$repo"
write_source_lines "$repo/src/diverged.rs" 1000
git -C "$repo" add src/diverged.rs
write_source_lines "$repo/src/diverged.rs" 1001
expect_rejected 'index 合规而工作树超长仍会失败' "$repo" 'src/diverged.rs'

# ignored、限定路径且有 FRB 文件头的 generated、固定 Cargokit vendored 路径不计入手写结构门禁。
repo=$(new_repo ignored-source)
printf '%s\n' 'ignored/' >"$repo/.gitignore"
commit_all "$repo"
write_source_lines "$repo/ignored/skipped.rs" 1001
expect_pass 'Git ignored 源码被排除' "$repo"

repo=$(new_repo generated-source)
write_generated_lines "$repo/crates/ubaa-flutter-bridge/src/frb_generated.rs" 1001
commit_all "$repo"
expect_pass '限定 Rust 路径且有 FRB 文件头的 generated 源码被排除' "$repo"

repo=$(new_repo generated-dart-source)
write_generated_lines "$repo/packages/ubaa_bindings/lib/src/rust/frb_generated.dart" 1001
commit_all "$repo"
expect_pass '限定 Dart 路径且有 FRB 文件头的 generated 源码被排除' "$repo"

repo=$(new_repo forged-generated-header)
write_generated_lines "$repo/src/forged.rs" 1001
commit_all "$repo"
expect_rejected '普通源码复制 FRB 文件头也会失败' "$repo" 'src/forged.rs'

repo=$(new_repo missing-generated-header)
write_source_lines "$repo/packages/ubaa_bindings/lib/src/rust/manual.dart" 1001
commit_all "$repo"
expect_rejected '限定生成路径缺少 FRB 文件头仍会失败' "$repo" 'packages/ubaa_bindings/lib/src/rust/manual.dart'

repo=$(new_repo vendored-source)
write_source_lines "$repo/packages/ubaa_bindings/cargokit/tool/src/large.cc" 1001
for number in {01..17}; do
  write_source_lines "$repo/packages/ubaa_bindings/cargokit/tool/src/file_${number}.hpp" 1
done
commit_all "$repo"
expect_pass '固定 Cargokit vendored 路径被排除' "$repo"

# baseline 语法拒绝重复、未知 kind、绝对路径和含 .. 的逃逸路径。
repo=$(new_repo duplicate-baseline)
write_source_lines "$repo/src/legacy.rs" 1001
printf 'file\tsrc/legacy.rs\t1001\n' >>"$repo/scripts/layout-baseline.txt"
printf 'file\tsrc/legacy.rs\t1001\n' >>"$repo/scripts/layout-baseline.txt"
commit_all "$repo"
expect_rejected '重复 baseline 项会失败' "$repo" 'src/legacy.rs'

repo=$(new_repo unknown-kind-baseline)
printf 'unknown\tsrc/legacy.rs\t1001\n' >>"$repo/scripts/layout-baseline.txt"
commit_all "$repo"
expect_rejected '未知 baseline kind 会失败' "$repo" 'src/legacy.rs'

repo=$(new_repo absolute-baseline)
printf 'file\t/tmp/outside.rs\t1001\n' >>"$repo/scripts/layout-baseline.txt"
commit_all "$repo"
expect_rejected '绝对 baseline 路径会失败' "$repo" '/tmp/outside.rs'

repo=$(new_repo escaping-baseline)
printf 'file\t../outside.rs\t1001\n' >>"$repo/scripts/layout-baseline.txt"
commit_all "$repo"
expect_rejected '含 .. 的 baseline 路径会失败' "$repo" '../outside.rs'

# 源码符号链接不能作为跟随仓库外文件的扫描入口。
repo=$(new_repo outside-symlink)
write_source_lines "$test_root/outside.rs" 1001
mkdir -p "$repo/src"
ln -s "$test_root/outside.rs" "$repo/src/outside.rs"
commit_all "$repo"
expect_rejected '源码符号链接不会跟随到仓库外' "$repo" 'src/outside.rs'

# 每种受支持扩展名都以真实超长 tracked 文件触发同一结构合同。
extensions=(rs dart kt kts ets ts tsx js java swift m mm c cc cpp h hpp sh)
for extension in "${extensions[@]}"; do
  repo=$(new_repo "extension-$extension")
  path="src/extension/sample.$extension"
  write_source_lines "$repo/$path" 1001
  commit_all "$repo"
  expect_rejected ".$extension 扩展名受扫描" "$repo" "$path"
done

printf '%s\n' "layout shell contracts passed: $pass_count"
