#!/usr/bin/env bash
# 检查手写源码的物理规模，并用精确 baseline 暂时登记当前已知违例。
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
if ! repo_root=$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null); then
  printf '%s\n' 'layout check: 无法从脚本位置定位 Git 仓库' >&2
  exit 1
fi
baseline_file="$repo_root/scripts/layout-baseline.txt"
if [[ ! -f "$baseline_file" ]]; then
  printf '%s\n' 'layout check: 缺少 scripts/layout-baseline.txt' >&2
  exit 1
fi

work_root=$(mktemp -d "${TMPDIR:-/tmp}/ubaa-layout-check.XXXXXX")
trap 'rm -rf -- "$work_root"' EXIT HUP INT TERM

index_dirs="$work_root/index-dirs.txt"
worktree_dirs="$work_root/worktree-dirs.txt"
violations_raw="$work_root/violations-raw.tsv"
violations="$work_root/violations.tsv"
baseline_entries="$work_root/baseline.tsv"
baseline_keys="$work_root/baseline-keys.tsv"
: >"$index_dirs"
: >"$worktree_dirs"
: >"$violations_raw"
: >"$baseline_entries"
: >"$baseline_keys"

error_count=0
blob_number=0

report_error() {
  error_count=$((error_count + 1))
  printf 'layout check: %s\n' "$1" >&2
}

is_source_path() {
  case $1 in
    *.rs | *.dart | *.kt | *.kts | *.ets | *.ts | *.tsx | *.js | *.java | *.swift | *.m | *.mm | *.c | *.cc | *.cpp | *.h | *.hpp | *.sh)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

is_vendored_path() {
  case $1 in
    packages/ubaa_bindings/cargokit/*) return 0 ;;
    *) return 1 ;;
  esac
}

is_frb_output_path() {
  case $1 in
    crates/ubaa-flutter-bridge/src/frb_generated.rs | packages/ubaa_bindings/lib/src/rust/*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

has_frb_generated_header() {
  local source_file=$1
  local header
  header=$(LC_ALL=C sed -n '1,8p' "$source_file")
  # 生成标记中的反引号是需要逐字匹配的文本。
  # shellcheck disable=SC2016
  [[ $header == *'This file is automatically generated, so please do not edit it.'* &&
    $header == *'@generated by `flutter_rust_bridge`@'* ]]
}

path_is_supported() {
  local path=$1
  if [[ $path == *$'\n'* || $path == *$'\t'* ]]; then
    report_error "源码路径包含不支持的换行或制表符：$path"
    return 1
  fi
  is_source_path "$path" || return 1
  is_vendored_path "$path" && return 1
  return 0
}

record_source_snapshot() {
  local path=$1
  local source_file=$2
  local directory_file=$3
  local line_count directory

  if is_frb_output_path "$path" && has_frb_generated_header "$source_file"; then
    return 0
  fi

  directory=$(dirname "$path")
  printf '%s\n' "$directory" >>"$directory_file"
  line_count=$(LC_ALL=C awk 'END { print NR }' "$source_file")
  if [[ $line_count -gt 1000 ]]; then
    printf 'file\t%s\t%s\n' "$path" "$line_count" >>"$violations_raw"
  fi
}

scan_index_path() {
  local path=$1
  local index_entry mode blob_file
  path_is_supported "$path" || return 0

  index_entry=$(git -C "$repo_root" ls-files -s -- "$path")
  mode=${index_entry%% *}
  if [[ $mode == 120000 ]]; then
    report_error "源码符号链接不允许：$path"
    return 0
  fi
  if [[ $mode != 100644 && $mode != 100755 ]]; then
    report_error "源码 index mode 不受支持（${mode}）：$path"
    return 0
  fi

  blob_number=$((blob_number + 1))
  blob_file="$work_root/index-blob-$blob_number"
  if ! git -C "$repo_root" show ":$path" >"$blob_file"; then
    report_error "无法读取 index blob：$path"
    return 0
  fi
  record_source_snapshot "$path" "$blob_file" "$index_dirs"
}

scan_worktree_path() {
  local path=$1
  local absolute_path="$repo_root/$path"
  path_is_supported "$path" || return 0

  if [[ -L "$absolute_path" ]]; then
    report_error "源码符号链接不允许：$path"
    return 0
  fi
  [[ -f "$absolute_path" ]] || return 0
  record_source_snapshot "$path" "$absolute_path" "$worktree_dirs"
}

if [[ -n $(git -C "$repo_root" ls-files -u) ]]; then
  report_error '仓库存在未解决的 index 冲突，无法建立结构快照'
else
  while IFS= read -r -d '' path; do
    scan_index_path "$path"
  done < <(git -C "$repo_root" ls-files -z --cached)

  while IFS= read -r -d '' path; do
    scan_worktree_path "$path"
  done < <(git -C "$repo_root" ls-files -z --cached --others --exclude-standard)
fi

record_directory_violations() {
  local directory_file=$1
  LC_ALL=C awk '
    { count[$0] += 1 }
    END {
      for (directory in count) {
        if (count[directory] > 16) {
          printf "dir\t%s\t%d\n", directory, count[directory]
        }
      }
    }
  ' "$directory_file" >>"$violations_raw"
}

record_directory_violations "$index_dirs"
record_directory_violations "$worktree_dirs"
LC_ALL=C sort -u "$violations_raw" >"$violations"

valid_baseline_path() {
  local kind=$1
  local path=$2
  case $path in
    '' | /*)
      return 1
      ;;
  esac
  case "/$path/" in
    */../* | */./* | *//*)
      return 1
      ;;
  esac
  if [[ $kind == file && $path == . ]]; then
    return 1
  fi
  return 0
}

while IFS= read -r line || [[ -n $line ]]; do
  [[ -z $line || $line == \#* ]] && continue

  line_without_tabs=${line//$'\t'/}
  tab_count=$((${#line} - ${#line_without_tabs}))
  if [[ $tab_count -ne 2 ]]; then
    report_error "baseline 必须恰有三列：$line"
    continue
  fi

  kind=${line%%$'\t'*}
  remainder=${line#*$'\t'}
  path=${remainder%%$'\t'*}
  count=${remainder#*$'\t'}

  if [[ $kind != file && $kind != dir ]]; then
    report_error "baseline kind 未知（${kind}）：$path"
    continue
  fi
  if ! valid_baseline_path "$kind" "$path"; then
    report_error "baseline 路径必须是仓库内规范相对路径：$path"
    continue
  fi
  case $count in
    '' | *[!0-9]*)
      report_error "baseline 数量必须是正整数：$path"
      continue
      ;;
  esac
  if [[ $count -le 0 ]]; then
    report_error "baseline 数量必须是正整数：$path"
    continue
  fi

  key="$kind"$'\t'"$path"
  if grep -Fqx -- "$key" "$baseline_keys"; then
    report_error "baseline 项重复：$path"
    continue
  fi
  printf '%s\n' "$key" >>"$baseline_keys"
  printf '%s\t%s\t%s\n' "$kind" "$path" "$count" >>"$baseline_entries"

  if [[ $kind == file ]]; then
    if [[ ! -e "$repo_root/$path" && ! -L "$repo_root/$path" ]]; then
      report_error "baseline 文件不存在：$path"
    fi
  elif [[ ! -d "$repo_root/$path" ]]; then
    report_error "baseline 目录不存在：$path"
  fi
done <"$baseline_file"

# baseline 的数量必须与 index/工作树任一现存违例快照精确一致；同一路径出现不同违例数量也会失败。
while IFS=$'\t' read -r kind path expected_count; do
  [[ -n $kind ]] || continue
  matching_counts=$(LC_ALL=C awk -F '\t' -v kind="$kind" -v path="$path" '
    $1 == kind && $2 == path { print $3 }
  ' "$violations")
  if [[ -z $matching_counts ]]; then
    report_error "baseline 项已不存在或已修复：$path"
    continue
  fi
  while IFS= read -r actual_count; do
    if [[ $actual_count != "$expected_count" ]]; then
      report_error "baseline 数量变化（登记 ${expected_count}，当前 ${actual_count}）：$path"
    fi
  done <<<"$matching_counts"
done <"$baseline_entries"

# 每项实际违例都必须有完全相同的 baseline 记录。
while IFS=$'\t' read -r kind path count; do
  [[ -n $kind ]] || continue
  entry="$kind"$'\t'"$path"$'\t'"$count"
  if ! grep -Fqx -- "$entry" "$baseline_entries"; then
    report_error "发现未登记或数量变化的结构违例（${kind}，${count}）：$path"
  fi
done <"$violations"

if [[ $error_count -ne 0 ]]; then
  printf 'layout check failed: %d 个问题\n' "$error_count" >&2
  exit 1
fi

violation_count=$(LC_ALL=C awk 'END { print NR }' "$violations")
printf 'layout check passed: %d 个精确 baseline 违例\n' "$violation_count"
