// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// P0 只用于证明 Dart、FRB 与 Rust 动态库真实连通。
String bridgeHello() => RustLib.instance.api.crateApiSimpleBridgeHello();
