// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'read.dart';

// These functions are ignored because they are not marked as `pub`: `cgyy_canonical`, `digest_bytes`, `digest`, `feature`, `invalid_input`, `map_cgyy_request`, `map_evaluation_course`, `map_resolution_error`, `now_seconds`, `operation`, `prepare_write`, `random_id`, `safe_message`, `text_shape`, `validate_cgyy_request`, `validate_id_i32`, `validate_id`, `validate_text`, `validate_ygdk_request`, `ygdk_canonical`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PendingEntry`, `PendingWrite`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BridgeBykcCourseRequest {
  final PlatformInt64 courseId;

  const BridgeBykcCourseRequest({required this.courseId});

  @override
  int get hashCode => courseId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcCourseRequest &&
          runtimeType == other.runtimeType &&
          courseId == other.courseId;
}

class BridgeBykcSignCourseRequest {
  final PlatformInt64 courseId;
  final double? lat;
  final double? lng;
  final int signType;

  const BridgeBykcSignCourseRequest({
    required this.courseId,
    this.lat,
    this.lng,
    required this.signType,
  });

  @override
  int get hashCode =>
      courseId.hashCode ^ lat.hashCode ^ lng.hashCode ^ signType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcSignCourseRequest &&
          runtimeType == other.runtimeType &&
          courseId == other.courseId &&
          lat == other.lat &&
          lng == other.lng &&
          signType == other.signType;
}

class BridgeCgyyCancelOrderRequest {
  final int id;

  const BridgeCgyyCancelOrderRequest({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyCancelOrderRequest &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

class BridgeCgyyReservationSelection {
  final int spaceId;
  final int timeId;
  final int? venueSpaceGroupId;

  const BridgeCgyyReservationSelection({
    required this.spaceId,
    required this.timeId,
    this.venueSpaceGroupId,
  });

  @override
  int get hashCode =>
      spaceId.hashCode ^ timeId.hashCode ^ venueSpaceGroupId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyReservationSelection &&
          runtimeType == other.runtimeType &&
          spaceId == other.spaceId &&
          timeId == other.timeId &&
          venueSpaceGroupId == other.venueSpaceGroupId;
}

class BridgeCgyySubmitReservationRequest {
  final int venueSiteId;
  final String reservationDate;
  final List<BridgeCgyyReservationSelection> selections;
  final String phone;
  final String theme;
  final int purposeType;
  final int joinerNum;
  final String activityContent;
  final String joiners;
  final bool isPhilosophySocialSciences;
  final bool isOffSchoolJoiner;

  const BridgeCgyySubmitReservationRequest({
    required this.venueSiteId,
    required this.reservationDate,
    required this.selections,
    required this.phone,
    required this.theme,
    required this.purposeType,
    required this.joinerNum,
    required this.activityContent,
    required this.joiners,
    required this.isPhilosophySocialSciences,
    required this.isOffSchoolJoiner,
  });

  @override
  int get hashCode =>
      venueSiteId.hashCode ^
      reservationDate.hashCode ^
      selections.hashCode ^
      phone.hashCode ^
      theme.hashCode ^
      purposeType.hashCode ^
      joinerNum.hashCode ^
      activityContent.hashCode ^
      joiners.hashCode ^
      isPhilosophySocialSciences.hashCode ^
      isOffSchoolJoiner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyySubmitReservationRequest &&
          runtimeType == other.runtimeType &&
          venueSiteId == other.venueSiteId &&
          reservationDate == other.reservationDate &&
          selections == other.selections &&
          phone == other.phone &&
          theme == other.theme &&
          purposeType == other.purposeType &&
          joinerNum == other.joinerNum &&
          activityContent == other.activityContent &&
          joiners == other.joiners &&
          isPhilosophySocialSciences == other.isPhilosophySocialSciences &&
          isOffSchoolJoiner == other.isOffSchoolJoiner;
}

class BridgeEvaluationSubmitCoursesRequest {
  final List<BridgeEvaluationCourse> courses;

  const BridgeEvaluationSubmitCoursesRequest({required this.courses});

  @override
  int get hashCode => courses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvaluationSubmitCoursesRequest &&
          runtimeType == other.runtimeType &&
          courses == other.courses;
}

class BridgeLibbookCancelBookingRequest {
  final String id;

  const BridgeLibbookCancelBookingRequest({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibbookCancelBookingRequest &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

class BridgeLibbookReserveRequest {
  final String areaId;
  final String seatId;
  final String day;
  final String segment;
  final String startTime;
  final String endTime;

  const BridgeLibbookReserveRequest({
    required this.areaId,
    required this.seatId,
    required this.day,
    required this.segment,
    required this.startTime,
    required this.endTime,
  });

  @override
  int get hashCode =>
      areaId.hashCode ^
      seatId.hashCode ^
      day.hashCode ^
      segment.hashCode ^
      startTime.hashCode ^
      endTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibbookReserveRequest &&
          runtimeType == other.runtimeType &&
          areaId == other.areaId &&
          seatId == other.seatId &&
          day == other.day &&
          segment == other.segment &&
          startTime == other.startTime &&
          endTime == other.endTime;
}

class BridgePhotoUpload {
  final Uint8List bytes;
  final String fileName;
  final String mimeType;

  const BridgePhotoUpload({
    required this.bytes,
    required this.fileName,
    required this.mimeType,
  });

  @override
  int get hashCode => bytes.hashCode ^ fileName.hashCode ^ mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePhotoUpload &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          fileName == other.fileName &&
          mimeType == other.mimeType;
}

class BridgeSigninPerformRequest {
  final String courseId;

  const BridgeSigninPerformRequest({required this.courseId});

  @override
  int get hashCode => courseId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSigninPerformRequest &&
          runtimeType == other.runtimeType &&
          courseId == other.courseId;
}

class BridgeWriteCommitResult {
  final BridgeWriteOperation operation;
  final bool success;
  final String message;
  final bool outcomeUnknown;
  final BridgeConnectionMode? resolvedRoute;
  final BridgeCgyyOrder? order;

  const BridgeWriteCommitResult({
    required this.operation,
    required this.success,
    required this.message,
    required this.outcomeUnknown,
    this.resolvedRoute,
    this.order,
  });

  @override
  int get hashCode =>
      operation.hashCode ^
      success.hashCode ^
      message.hashCode ^
      outcomeUnknown.hashCode ^
      resolvedRoute.hashCode ^
      order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWriteCommitResult &&
          runtimeType == other.runtimeType &&
          operation == other.operation &&
          success == other.success &&
          message == other.message &&
          outcomeUnknown == other.outcomeUnknown &&
          resolvedRoute == other.resolvedRoute &&
          order == other.order;
}

class BridgeWriteIntent {
  final String intentId;
  final BridgeWriteOperation operation;
  final String targetSummary;
  final BridgeConnectionMode resolvedRoute;
  final List<String> warnings;
  final PlatformInt64 expiresAt;
  final String requestDigest;

  const BridgeWriteIntent({
    required this.intentId,
    required this.operation,
    required this.targetSummary,
    required this.resolvedRoute,
    required this.warnings,
    required this.expiresAt,
    required this.requestDigest,
  });

  @override
  int get hashCode =>
      intentId.hashCode ^
      operation.hashCode ^
      targetSummary.hashCode ^
      resolvedRoute.hashCode ^
      warnings.hashCode ^
      expiresAt.hashCode ^
      requestDigest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWriteIntent &&
          runtimeType == other.runtimeType &&
          intentId == other.intentId &&
          operation == other.operation &&
          targetSummary == other.targetSummary &&
          resolvedRoute == other.resolvedRoute &&
          warnings == other.warnings &&
          expiresAt == other.expiresAt &&
          requestDigest == other.requestDigest;
}

enum BridgeWriteOperation {
  bykcSelectCourse,
  bykcDeselectCourse,
  bykcSignCourse,
  signinPerform,
  libbookReserve,
  libbookCancelBooking,
  ygdkSubmit,
  cgyySubmitReservation,
  cgyyCancelOrder,
  evaluationSubmitCourses,
}

class BridgeYgdkSubmitRequest {
  final int? itemId;
  final String? startTime;
  final String? endTime;
  final String? place;
  final bool? shareToSquare;
  final BridgePhotoUpload? photo;

  const BridgeYgdkSubmitRequest({
    this.itemId,
    this.startTime,
    this.endTime,
    this.place,
    this.shareToSquare,
    this.photo,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^
      startTime.hashCode ^
      endTime.hashCode ^
      place.hashCode ^
      shareToSquare.hashCode ^
      photo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeYgdkSubmitRequest &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          startTime == other.startTime &&
          endTime == other.endTime &&
          place == other.place &&
          shareToSquare == other.shareToSquare &&
          photo == other.photo;
}
