//! Core facade 与宿主绑定共享的稳定领域值。

mod action;
pub use action::*;
mod auth;
pub use auth::*;
mod route;
pub use route::*;
mod bykc;
pub use bykc::*;
mod libbook;
pub use libbook::*;
mod ygdk;
pub use ygdk::*;
mod evaluation;
pub use evaluation::*;
mod signin;
pub use signin::*;
mod schedule;
pub use schedule::*;
mod grades;
pub use grades::*;
mod classroom;
pub use classroom::*;
mod cgyy;
pub use cgyy::*;
mod spoc;
pub use spoc::*;
mod judge;
pub use judge::*;
